# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

# make necessary changes for your orderer descriptions please refer to notes 

  # add your orderer hostname for exemple (orderer.trade.com) : 
    container_name: # add container name 
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID= # add orderer local MSP ID as specified in configtx for exemple TradeOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/msp:/var/hyperledger/orderer/msp # change the directory before : to your directory under cryptoconfig 
    - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/tls/:/var/hyperledger/orderer/tls # change the directory before : to your directory under cryptoconfig 
    - orderer.trade.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

    # add your peers hostname for exemple peer0.exporterorg.trade.com:
    container_name: # add container name 
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exporterorg.trade.com
      - CORE_PEER_ADDRESS= # add peer hostname and port exemple peer0.exporterorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP= # add peer hostname and port exemple peer0.exporterorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT= # add peer hostname and port exemple peer0.exporterorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/msp:/etc/hyperledger/fabric/msp # change the directory before : to your directory under cryptoconfig 
        - ../crypto-config/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/tls:/etc/hyperledger/fabric/tls # change the directory before : to your directory under cryptoconfig 
        - peer0.exporterorg.trade.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060

    # add your other peers 

