# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.trade.com:
  peer0.exporterorg.trade.com:
  peer0.importerorg.trade.com:
  peer0.carrierorg.trade.com:
  peer0.regulatororg.trade.com:

networks:
  e-commerce: 

services:
  exporter-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-exporterorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ # add your ca public key exemple ca.exporterorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ # add your secret key EXPORTER_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.exporterorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/EXPORTER_CA_PRIVATE_KEY -b admin:adminpw -d' # make necessary changes for this command 
    volumes:
      - ./crypto-config/peerOrganizations/exporterorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config # change your ca directory under crypto config 
    container_name: ca_peerExporterOrg #change contrainer name 
    networks:
      - e-commerce
    
# add your other CAs

  orderer.trade.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.trade.com # change to the appropriate service under base/docker-compose-base
    container_name: orderer.trade.com # change your container name 
    networks:
      - e-commerce

  peer0.exporterorg.trade.com:
    container_name: peer0.exporterorg.trade.com # change your container name 
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporterorg.trade.com # change to the appropriate service under base/docker-compose-base
    networks:
      - e-commerce

# add your other peers 